### PR TITLE
Add `renderer` support and `HalfcellRenderer`.

### PR DESCRIPTION
**Pull request by JuerGenie**
- Add `renderer` argument for `Pixels.from_image` and `Pixels.from_image_path`.
- Add `HalfcellRenderer` and `FullcellRenderer`, make `renderer=HalfcellRenderer` to be default.
  - When use `HalfcellRenderer`, `Pixels` will render 2 pixels per character.
    ```python
    pixels = Pixels.from_image_path(images_path / "bulbasaur.png", renderer=HalfcellRenderer(default_color="black"))
    ```
  - When use `FullcellRenderer`, `Pixels` will render 1 pixel per 2 characters, just like before.
    ```python
    pixels = Pixels.from_image_path(images_path / "bulbasaur.png", renderer=FullcellRenderer())
    ```

image

### CODE REVIEW

**Comment by darrenburns** [comment]
Nice, this is great! Thank you!

I'd like to make this the default behaviour. 

I think it'd be better to avoid a boolean here, since there could be other renderers in the future (there are some even fancier approaches).

I'm thinking `renderer="halfcell"` or `renderer="fullcell"` would be the two options now. What do you think?

If you'd like to make this update, feel free. If not, let me know and I can do it :)

**Comment by JuerGenie** [comment]
> Nice, this is great! Thank you!
> 
> I'd like to make this the default behaviour.
> 
> I think it'd be better to avoid a boolean here, since there could be other renderers in the future (there are some even fancier approaches).
> 
> I'm thinking `renderer="halfcell"` or `renderer="fullcell"` would be the two options now. What do you think?
> 
> If you'd like to make this update, feel free. If not, let me know and I can do it :)

You're right, I'll make the changes later today ;D

**Comment by JuerGenie** [comment]
@darrenburns
Hi, I wrapped the rendering logic with the `Renderer` class, what do you think of this update? :D

**Comment by darrenburns** [comment]
Thank you! The new update is nicer. I'm going to make minor changes then release a new version. Appreciate your help :)

**Pull request merged**
